name: fitness
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.4
  provider: ^6.1.4
  intl: ^0.20.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/exercises/
    - assets/images/exercises/barbell_back_squat/barbell_back_squat_1.jpg
