// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIWSM6_9Uo_nsrors3KP45ivLR1t4x6o',
    appId: '1:831146661672:web:3a294b3f530cc7270f621d',
    messagingSenderId: '831146661672',
    projectId: 'fitness-46861',
    authDomain: 'fitness-46861.firebaseapp.com',
    databaseURL: 'https://fitness-46861-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-46861.firebasestorage.app',
    measurementId: 'G-D2H887PC07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0s82JlxlDveoFVPH4VRh95DN6LV4yFXU',
    appId: '1:831146661672:android:465ff54ceaa1070d0f621d',
    messagingSenderId: '831146661672',
    projectId: 'fitness-46861',
    databaseURL: 'https://fitness-46861-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-46861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTi8tMcQjKBRTEkipqe2_nMnKBhJvjxtk',
    appId: '1:831146661672:ios:6a67a4c0b14453d50f621d',
    messagingSenderId: '831146661672',
    projectId: 'fitness-46861',
    databaseURL: 'https://fitness-46861-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-46861.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTi8tMcQjKBRTEkipqe2_nMnKBhJvjxtk',
    appId: '1:831146661672:ios:6a67a4c0b14453d50f621d',
    messagingSenderId: '831146661672',
    projectId: 'fitness-46861',
    databaseURL: 'https://fitness-46861-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-46861.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbIWSM6_9Uo_nsrors3KP45ivLR1t4x6o',
    appId: '1:831146661672:web:e34e25633b696c2b0f621d',
    messagingSenderId: '831146661672',
    projectId: 'fitness-46861',
    authDomain: 'fitness-46861.firebaseapp.com',
    databaseURL: 'https://fitness-46861-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fitness-46861.firebasestorage.app',
    measurementId: 'G-5TF1W2952B',
  );

}